# NOTEBOOK 1 — Data Cleaning & Preparation
# Title : "North Africa M&E Dashboard — Data Preparation"
-----------------------------------------------------------------------------------------------------------------------------------------------------

### 📋 Project Overview

This project applies data science techniques to analyze health, governance, and food security indicators from FAO, WHO, and the World Bank across North Africa (Tunisia, Algeria, Morocco, Egypt, and Libya) between 2000 and 2023

It combines my background in **programme management and M&E** with newly acquired **data science skills** to produce evidence-based insights 
relevant to international development and evaluation work.

### 🎯 Key Questions
- How have food security indicators evolved across North Africa?
- Is there a correlation between governance quality and 
  food security outcomes?
- Can governance indicators predict undernourishment rates?
- How does Tunisia perform relative to the regional average?

The **First Step** is to clean and prepare the data for analysis.

## Objectives

- **Handle missing values**  
 Identify and manage incomplete data to ensure dataset integrity.  

- **Correct data formatting**  
  Apply consistent formatting practices to improve readability and usability of data.  

- **Standardize and normalize data**  
  Use preprocessing techniques to make variables comparable and prepare data for exploratory data analysis (EDA) and machine learning models.

- **Merge Data**
   Involves merging datasets from different sources

  ----------------------------------------------------------------------------------------------------------------------------------------------------

## Collect datasets

- **Dataset 1 — FAOSTAT (Suite of Food Security Indicators)**  
Food Security and Nutrition : https://www.fao.org/faostat/en/#data  
**Indicators:**<br>- Prevalence of undernourishment <br>- Food supply (kcal/capita/day)<br>- Access to safe drinking water   

- **Dataset 2 — World Bank Governance Indicators**  
https://databank.worldbank.org/source/worldwide-governance-indicators  
**Indicators:**<br>- Government Effectiveness<br>- Rule of Law<br>- Control of Corruption<br>- Voice and Accountability  

- **Dataset 3 — World Bank Governance Indicators**
https://www.who.int/data/gho/data/indicators  
**Indicators:**<br>- Life expectancy at birth<br>- Health expenditure (% of GDP)<br>- Maternal mortality ratio   

**Countries:** Tunisia, Algeria, Morocoo, Egypte, Libya   
**Year:** 2000 – 2023  

------------------------------------------------------------------------------------------------------------------------------------------------------

In [204]:

import pandas as pd
import numpy as np

# 1. load data
fao_data = pd.read_csv('faostat_food_security.csv') # https://www.fao.org/faostat/en  - "Food Security and Nutrition"
wb_data = pd.read_csv('worldbank_governance.csv') # https://databank.worldbank.org/source/worldwide-governance-indicators - World Bank Governance Indicators
who_data = pd.read_csv('who_health_indicators.csv') # https://www.who.int/data/gho/data/indicators - WHO Health Indicators

# 2. Inspect data FAO
fao_data.head(5)

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,FS,Suite of Food Security Indicators,12,Algeria,6121,Value,210041,Prevalence of undernourishment (percent) (3-ye...,20002002,2000-2002,%,7.3,E,Estimated value,NaN
1,FS,Suite of Food Security Indicators,12,Algeria,6121,Value,210041,Prevalence of undernourishment (percent) (3-ye...,20012003,2001-2003,%,6.7,E,Estimated value,NaN
2,FS,Suite of Food Security Indicators,12,Algeria,6121,Value,210041,Prevalence of undernourishment (percent) (3-ye...,20022004,2002-2004,%,6.4,E,Estimated value,NaN
3,FS,Suite of Food Security Indicators,12,Algeria,6121,Value,210041,Prevalence of undernourishment (percent) (3-ye...,20032005,2003-2005,%,6.4,E,Estimated value,NaN
4,FS,Suite of Food Security Indicators,12,Algeria,6121,Value,210041,Prevalence of undernourishment (percent) (3-ye...,20042006,2004-2006,%,6.1,E,Estimated value,NaN

In [205]:
missing_data_fao = fao_data.isnull()
missing_data_fao.head(5)

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [206]:
print(fao_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295 entries, 0 to 294
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       295 non-null    object
 1   Domain            295 non-null    object
 2   Area Code (M49)   295 non-null    int64
 3   Area              295 non-null    object
 4   Element Code      295 non-null    int64
 5   Element           295 non-null    object
 6   Item Code         295 non-null    int64
 7   Item              295 non-null    object
 8   Year Code         295 non-null    int64
 9   Year              295 non-null    object
 10  Unit              295 non-null    object
 11  Value             295 non-null    object
 12  Flag              295 non-null    object
 13  Flag Description  295 non-null    object
 14  Note              0 non-null      float64
dtypes: float64(1), int64(4), object(10)
memory usage: 34.7+ KB
None

In [207]:
print(fao_data.isnull().sum())  # missing values

Domain Code           0
Domain                0
Area Code (M49)       0
Area                  0
Element Code          0
Element               0
Item Code             0
Item                  0
Year Code             0
Year                  0
Unit                  0
Value                 0
Flag                  0
Flag Description      0
Note                295
dtype: int64

In [208]:
# 3. Cleaning
# Rename columns
fao_data.rename(columns={'Area': 'Country'}, inplace=True)
# Remove columns not useful in our analysis
fao_data = fao_data.drop(['Domain Code', 'Area Code (M49)', 'Element Code', 'Element', 'Flag', 'Note', 'Item Code', 'Flag Description', 'Year Code'], axis=1)

# Convert values to string first (if mixed types)
fao_data['Value'] = fao_data['Value'].astype(str)

# Replace "<2.5" with 2.49
fao_data['Value'] = fao_data['Value'].replace('<2.5', 2.49).astype(float)

In [209]:
fao_data.tail(5)

,Domain,Country,Item,Year,Unit,Value
290,Suite of Food Security Indicators,Tunisia,Percentage of population using safely managed ...,2018,%,75.0
291,Suite of Food Security Indicators,Tunisia,Percentage of population using safely managed ...,2019,%,75.0
292,Suite of Food Security Indicators,Tunisia,Percentage of population using safely managed ...,2020,%,74.0
293,Suite of Food Security Indicators,Tunisia,Percentage of population using safely managed ...,2021,%,74.0
294,Suite of Food Security Indicators,Tunisia,Percentage of population using safely managed ...,2022,%,74.0

In [210]:
# Since the World Bank governance file is annual, the most practical and consistent choice is to take the middle year of the FAO interval,
# because it represents the central point of the average.

# Function to convert interval (e.g., "2000-2002") into middle year (2001)
def convert_interval_to_middle(year_str):
    if "-" in year_str:
        start, end = year_str.split("-")
        start, end = int(start), int(end)
        middle = (start + end) // 2
        return middle
    else:
        return int(year_str)

# Apply conversion
fao_data["Year"] = fao_data["Year"].astype(str).apply(convert_interval_to_middle)

# Check result
fao_data.head(15)

,Domain,Country,Item,Year,Unit,Value
0,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2001,%,7.3
1,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2002,%,6.7
2,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2003,%,6.4
3,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2004,%,6.4
4,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2005,%,6.1
5,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2006,%,5.8
6,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2007,%,5.3
7,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2008,%,5.0
8,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2009,%,4.7
9,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2010,%,4.1
10,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2011,%,3.7
11,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2012,%,3.1
12,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2013,%,2.9
13,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2014,%,2.7
14,Suite of Food Security Indicators,Algeria,Prevalence of undernourishment (percent) (3-ye...,2015,%,2.6

In [212]:
# renaming the FAO “Item” column values into short, clear English names 

item_map = {
    'Prevalence of undernourishment (percent) (3-year average)': 'Undernourishment_pct',
    'Per capita food supply variability (kcal/cap/day)': 'FoodSupply_variability',
    'Percentage of population using safely managed drinking water services (percent)': 'SafeWater_pct'
}
fao_data['Item_short'] = fao_data['Item'].map(item_map)
fao_pivot = fao_data.pivot_table(
    index=['Country', 'Year'],
    columns='Item_short',
    values='Value',
    aggfunc='first'
).reset_index()
fao_pivot.columns.name = None

fao_pivot.head()

   Country  Year  FoodSupply_variability  SafeWater_pct  Undernourishment_pct
0  Algeria  2000                     NaN           70.0                   NaN
1  Algeria  2001                    30.0           71.0                   7.3
2  Algeria  2002                    29.0           71.0                   6.7
3  Algeria  2003                    23.0           72.0                   6.4
4  Algeria  2004                    25.0           72.0                   6.4

In [213]:
print(fao_pivot.isnull().sum())  # missing values

Country                    0
Year                       0
FoodSupply_variability     7
SafeWater_pct             49
Undernourishment_pct       3
dtype: int64

In [223]:
print("=== DIAGNOSTIC BEFORE IMPUTATION ===")
for col in ['Undernourishment_pct', 'SafeWater_pct', 'FoodSupply_variability']:
    print(f"\n{col} — missing values per country:")
    print(fao_pivot.groupby('Country')[col].apply(lambda x: x.isnull().sum()))

=== DIAGNOSTIC BEFORE IMPUTATION ===

Undernourishment_pct — missing values per country:
Country
Algeria    1
Egypt      0
Libya      0
Morocco    1
Tunisia    1
Name: Undernourishment_pct, dtype: int64

SafeWater_pct — missing values per country:
Country
Algeria     1
Egypt      23
Libya      23
Morocco     1
Tunisia     1
Name: SafeWater_pct, dtype: int64

FoodSupply_variability — missing values per country:
Country
Algeria    1
Egypt      0
Libya      4
Morocco    1
Tunisia    1
Name: FoodSupply_variability, dtype: int64

### ⚠️ Methodological Note — SafeWater_pct

Safe Water Access data (FAO) is **not available** for Egypt and Libya
for the period 2002–2023. These missing values have been **intentionally
retained as NaN** rather than imputed, as their absence reflects a
genuine data gap rather than a collection error.

Analyses involving this indicator are therefore **limited to Tunisia,
Algeria, and Morocco**.

This approach follows standard M&E practice:
*"The absence of data is itself an information."*

In [225]:
# ============================================================
# STEP 1 — Undernourishment_pct
# Linear interpolation by country (all countries combined)
# ============================================================
fao_pivot['Undernourishment_pct'] = fao_pivot.groupby('Country')['Undernourishment_pct'].transform(
    lambda x: x.interpolate(method='linear', limit_direction='both')
)
print("\n✅ Undernourishment_pct — linear interpolation applied")

✅ Undernourishment_pct — linear interpolation applied

In [226]:
# ============================================================
# STEP 2 — SafeWater_pct
# Linear interpolation ONLY for Tunisia, Algeria, Morocco
# Egypt and Libya → NaN intentionally preserved
# ============================================================
countries_with_data = ['Tunisia', 'Algeria', 'Morocco']

def impute_safewater(group):
    country = group['Country'].iloc[0]
    if country in countries_with_data:
        group['SafeWater_pct'] = group['SafeWater_pct'].interpolate(
            method='linear', limit_direction='both'
        )
    # Egypt and Libya → NaN intentionally kept
    return group
fao_pivot = fao_pivot.groupby('Country', group_keys=False).apply(impute_safewater)
print("✅ SafeWater_pct — linear interpolation applied for Tunisia, Algeria, Morocco")
print("✅ SafeWater_pct — NaN intentionally preserved for Egypt and Libya (FAO data not available)")

✅ SafeWater_pct — linear interpolation applied for Tunisia, Algeria, Morocco
✅ SafeWater_pct — NaN intentionally preserved for Egypt and Libya (FAO data not available)

C:\Users\abouf\AppData\Local\Temp\ipykernel_5508\804707522.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  fao_pivot = fao_pivot.groupby('Country', group_keys=False).apply(impute_safewater)

In [227]:
# ============================================================
# STEP 3 — FoodSupply_variability
# Median by country (volatile — resistant to outliers)
# ============================================================
fao_pivot['FoodSupply_variability'] = fao_pivot.groupby('Country')['FoodSupply_variability'].transform(
    lambda x: x.fillna(x.median())
)
print("✅ FoodSupply_variability — median by country applied")

✅ FoodSupply_variability — median by country applied

In [229]:
# ============================================================
# STEP 4 — FINAL CHECK
# ============================================================
print("\n=== MISSING VALUE AFTER IMPUTATION ===")
for col in ['Undernourishment_pct', 'SafeWater_pct', 'FoodSupply_variability']:
    print(f"\n{col}:")
    print(fao_pivot.groupby('Country')[col].apply(lambda x: x.isnull().sum()))

=== MISSING VALUE AFTER IMPUTATION ===

Undernourishment_pct:
Country
Algeria    0
Egypt      0
Libya      0
Morocco    0
Tunisia    0
Name: Undernourishment_pct, dtype: int64

SafeWater_pct:
Country
Algeria     0
Egypt      23
Libya      23
Morocco     0
Tunisia     0
Name: SafeWater_pct, dtype: int64

FoodSupply_variability:
Country
Algeria    0
Egypt      0
Libya      0
Morocco    0
Tunisia    0
Name: FoodSupply_variability, dtype: int64

In [233]:
# ============================================================
# STEP 5 — METHODOLOGICAL DOCUMENTATION
# ============================================================
imputation_log = pd.DataFrame({
    'Variable': [
        'Undernourishment_pct',
        'SafeWater_pct — Tunisia, Algeria, Morocco',
        'SafeWater_pct — Egypt, Libya',
        'FoodSupply_variability'
    ],
    'Method': [
        'Linear interpolation by country',
        'Linear interpolation by country',
        'No imputation — NaN retained',
        'Median by country'
    ],
    'Rationale': [
        'Gradual temporal trend — interpolation preserves trajectory',
        'Gradual temporal trend — interpolation appropriate',
        'Data not available from FAO — absence is informative, imputation would introduce bias',
        'Volatile indicator — median robust to extreme values'
    ]
})

print("\n=== METHODOLOGICAL DOCUMENTATION ===")
imputation_log

=== METHODOLOGICAL DOCUMENTATION ===

,Variable,Method,Rationale
0,Undernourishment_pct,Linear interpolation by country,Gradual temporal trend — interpolation preserv...
1,"SafeWater_pct — Tunisia, Algeria, Morocco",Linear interpolation by country,Gradual temporal trend — interpolation appropr...
2,"SafeWater_pct — Egypt, Libya",No imputation — NaN retained,Data not available from FAO — absence is infor...
3,FoodSupply_variability,Median by country,Volatile indicator — median robust to extreme ...

In [237]:
# 2. Inspect data WorldBank
wb_data = pd.read_csv('worldbank_governance.csv')
wb_data.head()

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],...,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,Algeria,DZA,Government Effectiveness - Governance score (0...,GOV_WGI_GE.SC,30.315712,37.372486,34.585084,38.10332,38.026452,37.049752,...,44.426893,43.087731,41.168188,45.716986,45.198171,46.103743,42.316215,46.146298,44.426943,46.456308
1,Algeria,DZA,Rule of Law - Governance score (0-100),GOV_WGI_RL.SC,35.789267,46.044672,46.047214,46.11783,44.169685,43.674394,...,41.863492,42.153281,42.032324,42.273948,42.409097,43.631675,43.964917,43.223943,44.350050,44.972685
2,Algeria,DZA,Control of Corruption - Governance score (0-100),GOV_WGI_CC.SC,26.714642,27.732560,31.331438,30.87151,35.274080,38.874555,...,35.103620,34.874320,36.914922,36.954486,35.294024,34.988608,34.677686,34.837964,34.905403,35.843598
3,Algeria,DZA,Voice and Accountability - Governance score (0...,GOV_WGI_VA.SC,35.494069,39.893884,38.333769,43.30096,44.517987,44.484855,...,44.147440,43.259642,43.023481,41.183089,38.370395,38.172666,38.594842,38.053596,38.482588,38.499523
4,Algeria,DZA,Voice and Accountability - Upper bound of the ...,GOV_WGI_VA.SC_UB,40.830457,44.658483,43.052936,47.28300,48.468111,48.434654,...,48.609255,47.721457,47.493347,45.974460,43.161766,42.986619,42.819087,42.277842,42.739323,42.756258

In [238]:
missing_data_wb = wb_data.isnull()
missing_data_wb.head(5)

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],...,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [239]:
print(wb_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 28 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   122 non-null    object
 1   Country Code   120 non-null    object
 2   Series Name    120 non-null    object
 3   Series Code    120 non-null    object
 4   2000 [YR2000]  120 non-null    float64
 5   2002 [YR2002]  120 non-null    float64
 6   2003 [YR2003]  120 non-null    float64
 7   2004 [YR2004]  120 non-null    float64
 8   2005 [YR2005]  120 non-null    float64
 9   2006 [YR2006]  120 non-null    float64
 10  2007 [YR2007]  120 non-null    float64
 11  2008 [YR2008]  120 non-null    float64
 12  2009 [YR2009]  120 non-null    float64
 13  2010 [YR2010]  120 non-null    float64
 14  2011 [YR2011]  120 non-null    float64
 15  2012 [YR2012]  120 non-null    float64
 16  2013 [YR2013]  120 non-null    float64
 17  2014 [YR2014]  120 non-null    float64
 18  2015 [YR2015]  120 non-null    float64
 19  2016 [YR2016]  120 non-null    float64
 20  2017 [YR2017]  120 non-null    float64
 21  2018 [YR2018]  120 non-null    float64
 22  2019 [YR2019]  120 non-null    float64
 23  2020 [YR2020]  120 non-null    float64
 24  2021 [YR2021]  120 non-null    float64
 25  2022 [YR2022]  120 non-null    float64
 26  2023 [YR2023]  120 non-null    float64
 27  2024 [YR2024]  120 non-null    float64
dtypes: float64(24), object(4)
memory usage: 27.5+ KB
None

In [240]:
print(wb_data.isnull().sum())  # missing values

Country Name     3
Country Code     5
Series Name      5
Series Code      5
2000 [YR2000]    5
2002 [YR2002]    5
2003 [YR2003]    5
2004 [YR2004]    5
2005 [YR2005]    5
2006 [YR2006]    5
2007 [YR2007]    5
2008 [YR2008]    5
2009 [YR2009]    5
2010 [YR2010]    5
2011 [YR2011]    5
2012 [YR2012]    5
2013 [YR2013]    5
2014 [YR2014]    5
2015 [YR2015]    5
2016 [YR2016]    5
2017 [YR2017]    5
2018 [YR2018]    5
2019 [YR2019]    5
2020 [YR2020]    5
2021 [YR2021]    5
2022 [YR2022]    5
2023 [YR2023]    5
2024 [YR2024]    5
dtype: int64

In [241]:
# --- Identify empty columns ---
empty_columns = wb_data.columns[wb_data.isnull().all()]
print("Empty columns:", empty_columns.tolist())

# --- Identify empty rows ---
empty_rows = wb_data[wb_data.isnull().all(axis=1)]
print("Number of completely empty rows:", len(empty_rows))

Empty columns: []
Number of completely empty rows: 3

In [242]:
# Find indexes of completely empty rows
empty_row_indexes = wb_data[wb_data.isnull().all(axis=1)].index
print("Indexes of empty rows:", empty_row_indexes.tolist())

Indexes of empty rows: [120, 121, 122]

In [243]:
wb_data.tail(10)

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],...,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
115,Tunisia,TUN,Rule of Law - Upper bound of the 90% confidenc...,GOV_WGI_RL.SC_UB,58.415913,58.020164,55.894526,59.307540,57.371552,59.778299,...,59.037339,59.255386,59.456163,60.077156,60.603031,61.072960,61.013016,57.121550,55.778595,54.902691
116,Tunisia,TUN,Rule of Law - Standard error of the governance...,GOV_WGI_RL.SE,0.208340,0.188943,0.188943,0.180678,0.175506,0.175506,...,0.140195,0.143322,0.143322,0.145278,0.145278,0.152651,0.152651,0.149943,0.149943,0.149198
117,Tunisia,TUN,Voice and Accountability - Governance estimate...,GOV_WGI_VA.EST,-1.071847,-1.132747,-1.118100,-1.158905,-1.183012,-1.131376,...,0.194739,0.214365,0.103586,0.085309,0.107612,0.106057,-0.062449,-0.415250,-0.505363,-0.683711
118,Tunisia,TUN,Voice and Accountability - Standard error of t...,GOV_WGI_VA.SE,0.185910,0.164408,0.164408,0.138727,0.138727,0.138727,...,0.122188,0.138273,0.138273,0.145936,0.145936,0.146385,0.146385,0.146385,0.147499,0.147499
119,Tunisia,TUN,Voice and Accountability - Number of sources,GOV_WGI_VA.SR,7.000000,10.000000,10.000000,13.000000,13.000000,13.000000,...,19.000000,17.000000,17.000000,15.000000,15.000000,14.000000,14.000000,14.000000,13.000000,13.000000
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Data from database: Worldwide Governance Indic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,Last Updated: 03/18/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [244]:
# Drop rows with index from 120 to 124 - missing values NaN
wb_data = wb_data.drop(wb_data.index[120:125])
wb_data.tail()

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],...,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
115,Tunisia,TUN,Rule of Law - Upper bound of the 90% confidenc...,GOV_WGI_RL.SC_UB,58.415913,58.020164,55.894526,59.307540,57.371552,59.778299,...,59.037339,59.255386,59.456163,60.077156,60.603031,61.072960,61.013016,57.121550,55.778595,54.902691
116,Tunisia,TUN,Rule of Law - Standard error of the governance...,GOV_WGI_RL.SE,0.208340,0.188943,0.188943,0.180678,0.175506,0.175506,...,0.140195,0.143322,0.143322,0.145278,0.145278,0.152651,0.152651,0.149943,0.149943,0.149198
117,Tunisia,TUN,Voice and Accountability - Governance estimate...,GOV_WGI_VA.EST,-1.071847,-1.132747,-1.118100,-1.158905,-1.183012,-1.131376,...,0.194739,0.214365,0.103586,0.085309,0.107612,0.106057,-0.062449,-0.415250,-0.505363,-0.683711
118,Tunisia,TUN,Voice and Accountability - Standard error of t...,GOV_WGI_VA.SE,0.185910,0.164408,0.164408,0.138727,0.138727,0.138727,...,0.122188,0.138273,0.138273,0.145936,0.145936,0.146385,0.146385,0.146385,0.147499,0.147499
119,Tunisia,TUN,Voice and Accountability - Number of sources,GOV_WGI_VA.SR,7.000000,10.000000,10.000000,13.000000,13.000000,13.000000,...,19.000000,17.000000,17.000000,15.000000,15.000000,14.000000,14.000000,14.000000,13.000000,13.000000

In [245]:
print(wb_data.isnull().sum())  # missing values

Country Name     0
Country Code     0
Series Name      0
Series Code      0
2000 [YR2000]    0
2002 [YR2002]    0
2003 [YR2003]    0
2004 [YR2004]    0
2005 [YR2005]    0
2006 [YR2006]    0
2007 [YR2007]    0
2008 [YR2008]    0
2009 [YR2009]    0
2010 [YR2010]    0
2011 [YR2011]    0
2012 [YR2012]    0
2013 [YR2013]    0
2014 [YR2014]    0
2015 [YR2015]    0
2016 [YR2016]    0
2017 [YR2017]    0
2018 [YR2018]    0
2019 [YR2019]    0
2020 [YR2020]    0
2021 [YR2021]    0
2022 [YR2022]    0
2023 [YR2023]    0
2024 [YR2024]    0
dtype: int64

In [246]:
'''
In practice, we will:
- Use the score (0–100) for comparisons across countries and years.
- Refer to the confidence interval (CI) and standard error (SI) when we want to highlight reliability and robust analysis:
 If SE is high → the score is less reliable → note this in your conclusions
 If CI is wide → large uncertainty → avoid over‑interpreting comparisons
# Practical rule:
 SE < 0.05 → Score is reliable ✅
 SE > 0.15 → Interpret with caution ⚠️

'''

# Keep only rows where 'Series Name' contains 'score' but NOT 'confidence interval'


wb_data_score = wb_data[
    wb_data['Series Name'].str.contains("score", case=False, na=False) &
    ~wb_data['Series Name'].str.contains("confidence interval", case=False, na=False)
]
wb_data_score.head(10)

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],...,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,Algeria,DZA,Government Effectiveness - Governance score (0...,GOV_WGI_GE.SC,30.315712,37.372486,34.585084,38.103320,38.026452,37.049752,...,44.426893,43.087731,41.168188,45.716986,45.198171,46.103743,42.316215,46.146298,44.426943,46.456308
1,Algeria,DZA,Rule of Law - Governance score (0-100),GOV_WGI_RL.SC,35.789267,46.044672,46.047214,46.117830,44.169685,43.674394,...,41.863492,42.153281,42.032324,42.273948,42.409097,43.631675,43.964917,43.223943,44.350050,44.972685
2,Algeria,DZA,Control of Corruption - Governance score (0-100),GOV_WGI_CC.SC,26.714642,27.732560,31.331438,30.871510,35.274080,38.874555,...,35.103620,34.874320,36.914922,36.954486,35.294024,34.988608,34.677686,34.837964,34.905403,35.843598
3,Algeria,DZA,Voice and Accountability - Governance score (0...,GOV_WGI_VA.SC,35.494069,39.893884,38.333769,43.300960,44.517987,44.484855,...,44.147440,43.259642,43.023481,41.183089,38.370395,38.172666,38.594842,38.053596,38.482588,38.499523
24,"Egypt, Arab Rep.",EGY,Government Effectiveness - Governance score (0...,GOV_WGI_GE.SC,46.398359,37.169443,38.918695,40.218153,39.070335,39.389655,...,41.197074,42.766630,43.428800,43.448433,49.033607,46.783658,46.963585,48.551605,50.567651,49.453283
25,"Egypt, Arab Rep.",EGY,Rule of Law - Governance score (0-100),GOV_WGI_RL.SC,54.936646,54.772490,54.687715,54.812758,53.290480,52.071966,...,42.539652,42.429177,43.633055,44.232988,44.067216,43.370310,42.877318,43.664053,43.580162,44.030180
26,"Egypt, Arab Rep.",EGY,Control of Corruption - Governance score (0-100),GOV_WGI_CC.SC,36.678482,35.494353,35.093066,35.108537,35.323971,36.266308,...,36.439136,38.801487,39.637467,38.240590,34.655137,31.834450,31.918264,32.113747,31.319427,31.115285
27,"Egypt, Arab Rep.",EGY,Voice and Accountability - Governance score (0...,GOV_WGI_VA.SC,35.323254,37.522366,37.220375,37.594800,38.047870,38.619041,...,34.503003,33.371173,33.533960,30.133575,29.347377,29.071144,27.830575,28.293850,28.799152,28.834153
48,Libya,LBY,Government Effectiveness - Governance score (0...,GOV_WGI_GE.SC,25.055811,22.961824,22.864299,27.492508,25.159815,25.503869,...,19.255654,18.932955,21.616129,21.172047,21.129356,19.593156,22.972692,20.935553,23.190418,23.739925
49,Libya,LBY,Rule of Law - Governance score (0-100),GOV_WGI_RL.SC,36.608131,33.211484,35.884530,37.522156,36.838640,37.317842,...,26.767514,27.774230,29.260199,29.970042,29.059644,28.851589,30.067925,26.963188,28.249118,27.740719

In [247]:
# Reshape: years as rows instead of columns
wb_data_score = wb_data_score.melt(
    id_vars = ["Country Name", "Country Code", "Series Name", "Series Code"],
    var_name = "Year",
    value_name = "Score"
)

# Extract year : '2000 [YR2000]' → 2000
wb_data_score['Year'] = wb_data_score['Year'].str.extract(r'(\d{4})').astype(int)

wb_data_score.head()

,Country Name,Country Code,Series Name,Series Code,Year,Score
0,Algeria,DZA,Government Effectiveness - Governance score (0...,GOV_WGI_GE.SC,2000,30.315712
1,Algeria,DZA,Rule of Law - Governance score (0-100),GOV_WGI_RL.SC,2000,35.789267
2,Algeria,DZA,Control of Corruption - Governance score (0-100),GOV_WGI_CC.SC,2000,26.714642
3,Algeria,DZA,Voice and Accountability - Governance score (0...,GOV_WGI_VA.SC,2000,35.494069
4,"Egypt, Arab Rep.",EGY,Government Effectiveness - Governance score (0...,GOV_WGI_GE.SC,2000,46.398359

In [248]:
wb_data_score = wb_data_score.drop(columns=['Country Code', 'Series Code'], axis=1)
wb_data_score = wb_data_score.rename(columns={'Country Name':'Country', 'Series Name':'Indicator'})
# Replace "Egypt, Arab Rep." with "Egypt" in the Country column
wb_data_score['Country'] = wb_data_score['Country'].replace("Egypt, Arab Rep.", "Egypt")
wb_data_score.head()

   Country                                          Indicator  Year      Score
0  Algeria  Government Effectiveness - Governance score (0...  2000  30.315712
1  Algeria             Rule of Law - Governance score (0-100)  2000  35.789267
2  Algeria   Control of Corruption - Governance score (0-100)  2000  26.714642
3  Algeria  Voice and Accountability - Governance score (0...  2000  35.494069
4    Egypt  Government Effectiveness - Governance score (0...  2000  46.398359

In [249]:
# renaming the WB “Indicator” column values into short, clear names 

indicator_map = {
    'Government Effectiveness - Governance score (0-100)': 'Gov_Effectiveness',
    'Rule of Law - Governance score (0-100)': 'Rule_of_Law',
    'Control of Corruption - Governance score (0-100)': 'Control_Corruption',
    'Voice and Accountability - Governance score (0-100)': 'Voice_Accountability'
}
wb_data_score['Item_short'] = wb_data_score['Indicator'].map(indicator_map)
wb_data_score = wb_data_score.pivot_table(
    index=['Country', 'Year'],
    columns='Item_short',
    values='Score',
    aggfunc='first'
).reset_index()
wb_data_score.columns.name = None

wb_data_score.head()

,Country,Year,Control_Corruption,Gov_Effectiveness,Rule_of_Law,Voice_Accountability
0,Algeria,2000,26.714642,30.315712,35.789267,35.494069
1,Algeria,2002,27.732560,37.372486,46.044672,39.893884
2,Algeria,2003,31.331438,34.585084,46.047214,38.333769
3,Algeria,2004,30.871510,38.103320,46.117830,43.300960
4,Algeria,2005,35.274080,38.026452,44.169685,44.517987

In [250]:
print(wb_data_score.isnull().sum())  # missing values

Country                 0
Year                    0
Control_Corruption      0
Gov_Effectiveness       0
Rule_of_Law             0
Voice_Accountability    0
dtype: int64

In [253]:
# 4. Merge datasets 
merged_data = pd.merge(fao_pivot, wb_data_score, on=['Country', 'Year'], how='inner') # FAO & WB

In [254]:
merged_data.head()

,Country,Year,FoodSupply_variability,SafeWater_pct,Undernourishment_pct,Control_Corruption,Gov_Effectiveness,Rule_of_Law,Voice_Accountability
0,Algeria,2000,30.0,70.0,7.3,26.714642,30.315712,35.789267,35.494069
1,Algeria,2002,29.0,71.0,6.7,27.732560,37.372486,46.044672,39.893884
2,Algeria,2003,23.0,72.0,6.4,31.331438,34.585084,46.047214,38.333769
3,Algeria,2004,25.0,72.0,6.4,30.871510,38.103320,46.117830,43.300960
4,Algeria,2005,25.0,73.0,6.1,35.274080,38.026452,44.169685,44.517987

In [256]:
# 2. Inspect data WHO Health 
who_data.head()

,country,date,Life_Expectancy,Health_Expenditure_GDP,Maternal_Mortality
0,Algeria,2023-01-01,76.261,4.350825,62.0
1,Algeria,2022-01-01,76.129,3.634643,64.0
2,Algeria,2021-01-01,75.208,5.021889,79.0
3,Algeria,2020-01-01,73.257,5.638308,97.0
4,Algeria,2019-01-01,75.682,5.417321,73.0

In [257]:
missing_data_who = who_data.isnull()
missing_data_who.head(5)

   country   date  Life_Expectancy  Health_Expenditure_GDP  Maternal_Mortality
0    False  False            False                   False               False
1    False  False            False                   False               False
2    False  False            False                   False               False
3    False  False            False                   False               False
4    False  False            False                   False               False

In [258]:
print(who_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 120 non-null    object
 1   date                    120 non-null    object
 2   Life_Expectancy         120 non-null    float64
 3   Health_Expenditure_GDP  120 non-null    float64
 4   Maternal_Mortality      120 non-null    float64
dtypes: float64(3), object(2)
memory usage: 4.8+ KB
None

In [259]:
print(who_data.isnull().sum())

country                   0
date                      0
Life_Expectancy           0
Health_Expenditure_GDP    0
Maternal_Mortality        0
dtype: int64

In [260]:
# Extract year
who_data['date'] = who_data['date'].str[:4].astype(int)

print(who_data['date'].head())

0    2023
1    2022
2    2021
3    2020
4    2019
Name: date, dtype: int64

In [261]:
who_data = who_data.rename(columns={'date':'Year', 'country' : 'Country'})

In [262]:
who_data['Country'].value_counts()

Country
Algeria             24
Egypt, Arab Rep.    24
Libya               24
Morocco             24
Tunisia             24
Name: count, dtype: int64

In [263]:
who_data['Country'] = who_data['Country'].replace("Egypt, Arab Rep.", "Egypt")
who_data['Country'].value_counts()

Country
Algeria    24
Egypt      24
Libya      24
Morocco    24
Tunisia    24
Name: count, dtype: int64

In [264]:
# 4. Merge all datasets 
merged_data = pd.merge(merged_data, who_data, on=['Country', 'Year'], how='inner') # FAO & WB & WHO

In [268]:
# ============================================================
# Reorder Columns
# ============================================================
cols_order = [
    'Country', 'Year',
    # FAO indicators
    'Undernourishment_pct',
    'FoodSupply_variability',
    'SafeWater_pct',
    # Health indicators
    'Life_Expectancy',
    'Health_Expenditure_GDP',
    'Maternal_Mortality',
    # Governance indicators
    'Gov_Effectiveness',
    'Rule_of_Law',
    'Control_Corruption',
    'Voice_Accountability'
]

# Garder seulement les colonnes qui existent
cols_order = [c for c in cols_order if c in merged_data.columns]
merged_data = merged_data[cols_order]

# ============================================================
# 5. Export data for Power BI
# ============================================================
!pip install openpyxl

merged_data.to_csv('north_africa_final_clean.csv', index=False)
merged_data.to_excel('north_africa_final_clean.xlsx', index=False)

print("✅ File created successfully!")
print(f"Shape: {merged_data.shape}")
print(f"Columns: {merged_data.columns.tolist()}")
print(f"Country: {sorted(merged_data['Country'].unique())}")
print(f"Years: {sorted(merged_data['Year'].unique())}")
print()
merged_data.head(10)

Requirement already satisfied: openpyxl in C:\Users\abouf\anaconda3\envs\RP_Env\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\abouf\anaconda3\envs\RP_Env\Lib\site-packages (from openpyxl) (2.0.0)
✅ File created successfully!
Shape: (113, 12)
Columns: ['Country', 'Year', 'Undernourishment_pct', 'FoodSupply_variability', 'SafeWater_pct', 'Life_Expectancy', 'Health_Expenditure_GDP', 'Maternal_Mortality', 'Gov_Effectiveness', 'Rule_of_Law', 'Control_Corruption', 'Voice_Accountability']
Country: ['Algeria', 'Egypt', 'Libya', 'Morocco', 'Tunisia']
Years: [np.int64(2000), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023)]

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

,Country,Year,Undernourishment_pct,FoodSupply_variability,SafeWater_pct,Life_Expectancy,Health_Expenditure_GDP,Maternal_Mortality,Gov_Effectiveness,Rule_of_Law,Control_Corruption,Voice_Accountability
0,Algeria,2000,7.3,30.0,70.0,70.576,3.214854,123.0,30.315712,35.789267,26.714642,35.494069
1,Algeria,2002,6.7,29.0,71.0,71.644,3.441696,102.0,37.372486,46.044672,27.732560,39.893884
2,Algeria,2003,6.4,23.0,72.0,71.906,3.325694,101.0,34.585084,46.047214,31.331438,38.333769
3,Algeria,2004,6.4,25.0,72.0,72.536,3.290305,91.0,38.103320,46.117830,30.871510,43.300960
4,Algeria,2005,6.1,25.0,73.0,72.836,3.118861,87.0,38.026452,44.169685,35.274080,44.517987
5,Algeria,2006,5.8,30.0,73.0,73.116,3.189999,84.0,37.049752,43.674394,38.874555,44.484855
6,Algeria,2007,5.3,30.0,74.0,73.346,3.620114,83.0,36.724100,44.308687,38.152088,43.881066
7,Algeria,2008,5.0,32.0,74.0,73.618,3.983310,83.0,37.255954,43.982875,36.074908,43.213119
8,Algeria,2009,4.7,30.0,75.0,73.871,4.892108,83.0,37.761123,43.208216,35.403078,41.829067
9,Algeria,2010,4.1,26.0,75.0,74.144,4.640014,82.0,39.620660,43.711008,39.923053,41.350006

In [269]:
print(merged_data.isnull().sum())

Country                    0
Year                       0
Undernourishment_pct       0
FoodSupply_variability     0
SafeWater_pct             44
Life_Expectancy            0
Health_Expenditure_GDP     0
Maternal_Mortality         0
Gov_Effectiveness          0
Rule_of_Law                0
Control_Corruption         0
Voice_Accountability       0
dtype: int64